language: python
dist: trusty
cache:
    apt: true
    pip: true
python:
  - "2.7"
  - "3.5"
  - "3.6"
services:
  docker
install:
  - travis_retry sudo add-apt-repository -y ppa:octave/stable
  - travis_retry sudo apt-get update -qq
  - travis_retry sudo apt-get install -y octave liboctave-dev
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install -c conda-forge pip
  - pip install .
  - make docker-build
script:
  - make test
  - python -m octave_kernel install --user
notifications:
  email:
    - steven.silvester@ieee.org
